### PR TITLE
Fix typos - Update ReadMe.md

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
This seems like an interesting package, and I noticed BoltExt. What is (Bolt.jl that I found, and, possibly synonym) BoltExt?

It's not registered, does that matter for you?
https://github.com/xzackli/Bolt.jl

You claim you don't need e.g. Python, while you depend on PythonCall.jl. That's for optional Python package then, but is it slower to depend on it when not using? I forget how to optionally depend on a package, I think it's Require.jl.

**Comment by JaimeRZP** [comment]
Hi!
Thank you so much for looking into this!

> This seems like an interesting package, and I noticed BoltExt. What is (Bolt.jl that I found, and, possibly synonym) BoltExt?
> It's not registered, does that matter for you? https://github.com/xzackli/Bolt.jl

Bolt.jl is a library that solves the Boltzmann-Einstein equations to find the distribution of different species of matter right after the big bang. It's role is to provide an alternative way to compute certain related quantites to LimberJack. Hence, why it is an extension. Indeed, it is not registered which is creating issues registering LimberJack itself. 

> You calim you don't need e.g. Python, while you depend on PythonCall.jl. That's for optional Python package then, but is it slower to depend on it when not using? I forget how to optionally depend on a package, I think it's Require.jl.

LimberJack itself doesn't depend on any python method. But Astronomers love to use python data structures that we need to support to allow interoperability with other tools.

**Comment by PallHaraldsson** [comment]
I think you can merge the PR. I didn't plan more here, was just using this space to ask out of curiosity (are you ok with more, here?) And I'm not objecting to PythonCalll.jl strictly (it's great), still it has a bit longer startup than I would prefer, so lazy loading it might be valuable, or just not worry and wait for its startup to improve. Anyway, lazy loading will likely not be a PR from me, at least not part of this one. It's simple though I believe (if most use with Python, and the optional package you suggested anyway, might not be worth it. I just wasn't sure, it at least still seems optional, so potentially used with no Python).

**Comment by JaimeRZP** [comment]
Hi!

I will close this and we can keep talking on an issue!

Thank you once again for the PR!

**Pull request merged**
